Readme.md
source/aasm/tensor-ir.lisp
source/air/node.lisp
source/ajit/backends/clang.lisp
source/ajit/scheduler.lisp
source/ajit/simplifiers.lisp
source/apis/ahead-of-time.lisp
source/apis/function.lisp
source/apis/iseq.lisp
source/apis/package.lisp
source/apis/tensor.lisp
source/apis/test-suites.lisp
source/avm/opset.lisp
source/avm/runtime.lisp
source/common/caten.common.asd
source/common/contextvar.lisp

- Compiled aIR graph are only composed of number, symbol, and keyword. they can be dumped using `make-load-form`.

AOT Compilation, Shape Inference

---

source/aasm/constant-folding.lisp
source/aasm/tensor-ir.lisp
source/aasm/test-suites.lisp
source/ajit/backends/clang.lisp
source/ajit/graph.lisp
source/ajit/helpers.lisp
source/ajit/polyhedral.lisp
source/ajit/renderer.lisp
source/ajit/scheduler.lisp
source/ajit/simplifiers.lisp
source/apis/initializers.lisp
source/apis/iseq.lisp
source/apis/test-suites.lisp
source/avm/test-suites.lisp

- Fix: val_xxx is undeclared
- Enumerate all save-for-backward existing in the graph before start compilation
- Move on another PR
(After this PR merged, let's start working on OpenCL/METAL Backends or improving the polyhedral compiler to support OMP, vectorization, 4x4 accumulation for gemm, etc)

[Draft] Make JIT completely equivalent to VM (Forward Mode)

---

.github/workflows/tests_on_push.yml
source/ajit/helpers.lisp
source/ajit/scheduler.lisp

Patch for CCL and ECL

---

caten.asd
external/llm/layers.lisp
external/llm/package.lisp
source/air/attr.lisp
source/apis/initializers.lisp
source/apis/iseq.lisp
source/nn/activations.lisp
source/nn/embedding.lisp
source/test-suite/caten.test-suite.asd
source/test-suite/package.lisp
source/test-suite/test-iseq-lowerer.lisp
source/test-suite/test-randomness.lisp

[BugFix] Eliminate Known issues in Simplifier

---

source/ajit/isl-ast-helpers.lisp
source/ajit/render-graph.lisp
source/ajit/test-suites.lisp
source/ajit/transform.lisp
source/apis/initializers.lisp
source/apis/iseq.lisp
source/common/contextvar.lisp
source/isl/isl-object.lisp
source/nn/activations.lisp

```
val_445[(_gid0+0)] = (val_456_0^((val_445[(_gid0+0)]*32768)+(uint32_t)((float)val_445[(_gid0+0)]*7.6293945e-6)));
->
float _tmp_0 = val_445[_gid0+0];
val_445[_gid0+0] = (val_456_0^((_tmp_0*32768)+(uint32_t)((float)_tmp_0*7.6293945e-6)));
```
```clang
void main500811_e229_k0(uint32_t* val_400, uint32_t* val_123, uint32_t val_397) {
(*val_123) = 4;
(*val_400) = (val_397+(*val_123));
uint32_t val_124 = (*val_400);
}
```
```
```

Post-MultiExpr Fusion in the equivalent domain

---

source/ajit/backends/clang.lisp
source/ajit/isl-ast-helpers.lisp
source/ajit/multiexpr.lisp
source/ajit/test-suites.lisp
source/ajit/transform.lisp

```
val_445[(_gid0+0)] = (val_456_0^((val_445[(_gid0+0)]*32768)+(uint32_t)((float)val_445[(_gid0+0)]*7.6293945e-6)));
->
float _tmp_0 = val_445[_gid0+0];
val_445[_gid0+0] = (val_456_0^((_tmp_0*32768)+(uint32_t)((float)_tmp_0*7.6293945e-6)));
```
```clang
void main500811_e229_k0(uint32_t* val_400, uint32_t* val_123, uint32_t val_397) {
(*val_123) = 4;
(*val_400) = (val_397+(*val_123));
uint32_t val_124 = (*val_400);
}
```

JIT: Post-MultiExpr Optimization between different iteration spaces (Final)

---

source/ajit/memory-planner.lisp
source/ajit/polyhedral-group.lisp
source/ajit/scheduler.lisp
source/apis/tensor.lisp
source/common/contextvar.lisp

Fix: Propagate Scalar anywhere

---

source/aasm/attrs.lisp
source/apis/iseq.lisp
source/codegen/blueprint.lisp
source/codegen/expr-cache.lisp
source/codegen/exprify.lisp
source/codegen/jit.lisp
source/codegen/rewriting-rules.lisp

`:MOVE` is an operation where:
```
A <- MOVE(B, C)
```
Destructivey moves all the visible elements of C into B, the address of `A` is the address of `B` (to keep DAG)

Introduce Pointer Adress to caten/aasm, and revisit the semantic of :MOVE

---

source/codegen/blueprint.lisp
source/codegen/exprify.lisp
source/codegen/helpers.lisp
source/codegen/jit.lisp
source/codegen/rewriting-rules.lisp
source/codegen/scheduler.lisp
source/test-suite/test-schedule.lisp

I have found two failing case for symbolic (which would be prepreq for full symbolic transformer)
```
(caten (!sin (make-tensor `(,(!add (make-tensor `(1)) (iconst 'n))))))
(caten (!add (!add (!index-components `(5)) (!add caten/apis::*rng-counter* (!* (iconst 2) (iconst 'n)) :reduce t))
(!* (iconst 2) (iconst 'n))))
```

Fix: Scalar mutated by try-insert-node is not a pointer

---

source/aasm/constant-folding.lisp
source/aasm/test-suites.lisp
source/air/package.lisp
source/air/pattern-matcher.lisp
source/air/test-suites.lisp
source/apis/helpers.lisp
source/apis/iseq.lisp
source/apis/test-suites.lisp
source/codegen/expr.lisp

Refactor: fold-constant without recursive function call

---

.github/workflows/tests_on_push.yml
.gitignore
source/aasm/constant-folding.lisp
source/aasm/optimizers.lisp
source/air/pattern-matcher.lisp
source/apis/iseq.lisp
source/common/contextvar.lisp

```
CATEN/LLM> (defparameter *transformer* (time (caten (forward *model* (make-tensor `(10 32)) (iconst 1)))))
COMPOSE-VIEWS-FROM-GRAPH: 56095 calls for 2302 nodes (24.36794%)
APPLY-FOLD-CONSTANT: 5205 calls for 1871 nodes (2.7819347%)
FUSE-VMOPS: 1748 calls for 1748 nodes (1.0%)
Evaluation took:
0.796 seconds of real time
0.778812 seconds of total run time (0.686056 user, 0.092756 system)
97.86% CPU
599,419,392 bytes consed
*TRANSFORMER*
CATEN/LLM> 
```

defsimplifier is O(N)

---

external/llm/layers.lisp
source/test-suite/test-llm.lisp
source/test-suite/test-regression-test.lisp

Refactor: MultiHeadAttention

---

source/codegen/memory-planner.lisp

fix for
```
(caten (!where (make-tensor `(s s s s)) (make-tensor `(s s s s)) (make-tensor `(s s s s))))
```

Refactor: Memory Planner Newid creates seen

---

source/codegen/polyhedral-ast.lisp

Fix for the following error message when compiling with Clozure CL
```
; While executing: ALEXANDRIA:SIMPLE-STYLE-WARNING, in process listener(1).
> Error: Symbol ASTBLOCK is unbound in namespace PATTERN
> While executing: PATTERN-EXPAND-1, in process listener(1).
> Type :GO to continue, :POP to abort, :R for a list of available restarts.
> If continued: Skip evaluation of (ros:run '((:eval"(ros:quicklisp)")(:source-registry ".")(:eval "(asdf:compile-system \"caten\" :verbose t)")))
> Type :? for other options.
```

BugFix: Fix structures to be visible at compile time from `trivia` library

---

source/air/viz.lisp
source/codegen/jit.lisp
source/codegen/memory-planner.lisp
source/codegen/scheduler.lisp
source/test-suite/helpers.lisp
source/test-suite/test-llm.lisp
source/test-suite/test-shape-tracker.lisp

BugFix: MHA in rtol<1e-5

---

external/benchmarks/benchmark-simplifier.lisp
source/codegen/blueprint.lisp
source/codegen/expr.lisp
source/codegen/exprify.lisp
source/test-suite/test-dynamic-shape.lisp

Opt: Faster Symbolic Lowerer

---

source/codegen/jit.lisp
source/codegen/scheduler.lisp
source/test-suite/test-dynamic-shape.lisp
source/test-suite/test-scheduler.lisp

more tests on symbolic

---

apps/gpt2/gpt2.lisp
external/llm/layers.lisp
source/apis/documentation.lisp
source/apis/function.lisp
source/apis/package.lisp
source/avm/lisp-backend.lisp
source/codegen/exprify.lisp
source/codegen/jit.lisp
source/codegen/scheduler.lisp
source/codegen/shape-inference.lisp
source/test-suite/test-dynamic-shape.lisp
source/test-suite/test-llm.lisp
source/test-suite/test-ops.lisp
source/test-suite/test-scheduler.lisp

BugFix: JIT=1 should support !assign to get KVCache worked.

---

asdf-load-caten.lisp

This adds asdf-load-caten.lisp which enables just loading Caten from Slime, the REPL, etc. without using ros.

enable (simple) loading of Caten via the REPL/Slime (without using ros)

---

Readme.md
external/backends/metal.lisp

Minimal Metal GPU Support

---

source/codegen/scop.lisp
source/codegen/shape-inference.lisp
source/test-suite/test-scheduler.lisp

Enhancement: Symbolic Loop Merge Dims

---

source/apis/helpers.lisp
source/apis/merge-views.lisp
source/codegen/shape-inference.lisp
source/test-suite/test-schedule-cache.lisp
source/test-suite/test-scheduler.lisp

#359 
```
(caten (!softmax (make-tensor `(,(!add (iconst 'n) (iconst 's)) n s))))
(caten (!matmul (make-tensor `(,(!add (iconst 'a) (iconst 'b)) 512 256)) (make-tensor `(256 1024))))
(with-inference-mode ()
(caten (!add (call (Embedding 10 10) (make-tensor `(10 10))) (call (Embedding 10 10) (!cast (!add (iconst 'n) (!index-components `(1 10))) :float32)))))
(with-inference-mode ()
(caten (!add (call (Embedding 10 10) (make-tensor `(10 10))) (call (Embedding 10 10) (make-tensor `(1 10))))))
(caten (!matmul (make-tensor `(1 s 64)) (!t (make-tensor `(128 64)))))
```

Full Symbolic Loop Collapse

---

.github/workflows/docs.yml
.github/workflows/tests_on_push.yml
source/apis/helpers.lisp
source/apis/package.lisp
source/avm/buffer.lisp
source/avm/helpers.lisp
source/avm/package.lisp
source/avm/runtime.lisp
source/common/contextvar.lisp

- Backend is determined the moment users called caten
- Each buffer allocation belongs to AVM
```
source/apis/ahead-of-time.lisp:  (defparameter *aot-jit* (ctx:getenv :AOT))
source/apis/ahead-of-time.lisp:  (defparameter *aot-vm* (ctx:getenv :AOT_VM))
source/apis/iseq.lisp:(defparameter *jit-device* nil)
source/avm/buffer.lisp:(defparameter *device* :lisp "a keyword to indicate the device (being dispatched)")
source/avm/runtime.lisp:(defparameter *vm* nil)
```

Refactor: one device corresponds to one backend

---

.github/workflows/tests_on_push.yml

CI: Remove CCL Support

---

docs/end-to-end-example.lisp
docs/getting-started.lisp
external/gguf/helpers.lisp
external/onnx/defop.lisp
source/aasm/tensor-ir.lisp
source/apis/attrs.lisp
source/apis/facets.lisp
source/apis/function.lisp
source/apis/helpers.lisp
source/apis/high-level-ops.lisp
source/apis/initializers.lisp
source/apis/iseq.lisp
source/apis/merge-views.lisp
source/apis/module.lisp
source/apis/shape-tracker.lisp
source/apis/tensor.lisp
source/common/contextvar.lisp
source/common/dtype.lisp
source/test-suite/test-air.lisp

some minor edits/improvements/fixes:
* move declaims about dtypes
(declaim (inline caten/common.dtype:encode-float64 caten/common.dtype:decode-float32 caten/common.dtype:encode-float64 caten/common.dtype:decode-float64))
from external/gguf/helpers.lisp to source/common/dtype.lisp
* fix end-to-end-example.lisp
* more information/slight restructuring in getting-started.lisp
* some edits in messages/comments (mostly in the caten/apis package)

some minor example/documentation/messages fixes and improvements

---

source/byoc/caten.byoc.asd
source/byoc/helpers/callback.lisp
source/byoc/metal.lisp
source/byoc/native.lisp
source/codegen/exprify.lisp
source/codegen/jit.lisp

Use MTLCodegen Directly

---

Readme.md
source/codegen/auto-scheduler/auto-scheduler.lisp
source/codegen/expr.lisp
source/common/dtype.lisp
source/test-suite/helpers.lisp
source/test-suite/test-activations.lisp
source/test-suite/test-apis.lisp
source/test-suite/test-ops.lisp

Once i passed metal tests, the next pr would be webgpu/opencl supports. and stable diffusion or beam

tweak on metal ci
