hikettei/Caten

caten.asd
source/aasm/caten.aasm.asd
source/air/caten.air.asd
source/ajit/caten.ajit.asd
source/ajit/test-suites.lisp
source/apis/caten.apis.asd
source/apis/test-suites.lisp
source/avm/caten.avm.asd
source/nn/caten.nn.asd
source/test-suite/caten.test-suite.asd
source/test-suite/package.lisp

CI: Improvements on CI and Testing

---

source/ajit/simplifiers.lisp
source/apis/ahead-of-time.lisp
source/apis/initializers.lisp
source/apis/test-suites.lisp

BugFix: Fix for recursive deps

---

source/air/caten.air.asd
source/air/package.lisp
source/air/viz.lisp
source/apis/iseq.lisp
source/common/contextvar.lisp

- `DOT=1` to render the lowered graph

Enhancement: DOT=1

---

source/ajit/polyhedral.lisp
source/ajit/scheduler.lisp
source/ajit/test-suites.lisp
source/ajit/transform.lisp

maximize_band_depth and Loop Fusion

---

source/apis/function.lisp

- This patch should make Lisp+VM Test green

Much Simplifier View Backward

---

source/codegen/blueprint.lisp
source/codegen/memory-planner.lisp
source/codegen/test-suites.lisp
source/test-suite/caten.test-suite.asd
source/test-suite/test-conv.lisp
source/test-suite/test-dynamic-shape.lisp
source/test-suite/test-llm.lisp
source/test-suite/test-memory-planner.lisp
source/test-suite/test-schedule.lisp

Fix: MergeDims

---

source/codegen/blueprint.lisp
source/codegen/expr.lisp
source/codegen/jit.lisp
source/codegen/scheduler.lisp
source/test-suite/test-schedule.lisp

Finish Scheduler and Lowerer Things

---

.github/workflows/tests_on_push.yml
caten.asd
external/benchmarks/benchmark-simplifier.lisp
external/benchmarks/package.lisp
roswell/caten.ros
source/apis/helpers.lisp
source/apis/tensor.lisp

Add: caten/benchmark for profiling the compilation time in CI

---

source/air/graph.lisp
source/air/package.lisp
source/apis/iseq.lisp

Opt: remove verify-graph for 10x time faster lowerer

---

source/apis/merge-views.lisp
source/avm/buffer.lisp
source/avm/helpers.lisp
source/avm/lisp-backend.lisp
source/codegen/jit.lisp
source/test-suite/test-conv.lisp
source/test-suite/test-shape-tracker.lisp

BugFix: Permute+Reshape(Uprank) Shape Tracker Merging for ConvND

---

source/codegen/expr.lisp
source/codegen/exprify.lisp
source/codegen/jit.lisp
source/codegen/memory-planner.lisp
source/codegen/renderer.lisp
source/codegen/scheduler.lisp
source/test-suite/test-view.lisp

BugFix: ExprGraph(x = y + y)

---

.github/workflows/docs.yml
mkdocs.yml

now english theme was officialy supported thanks to https://github.com/WSOFT-Project/lantana/issues/58#issuecomment-2479796246

Docs: Support English

---

external/benchmarks/benchmark-simplifier.lisp
source/codegen/backends/clang.lisp
source/codegen/blueprint.lisp
source/codegen/helpers.lisp
source/codegen/jit.lisp
source/codegen/scheduler.lisp
source/test-suite/test-dynamic-shape.lisp

#196 
after merging this, todo:

Support Full Symbolic JIT (Allow duplicated seen for ds)

---

apps/gpt2/gpt2.lisp
external/benchmarks/benchmark-simplifier.lisp
external/llm/layers.lisp
roswell/caten.ros
source/codegen/blueprint.lisp
source/codegen/expr.lisp
source/test-suite/test-schedule-cache.lisp

Feat: KVCache GPT2

---

source/apis/initializers.lisp
source/test-suite/helpers.lisp
source/test-suite/test-conv.lisp
source/test-suite/test-dynamic-shape.lisp
source/test-suite/test-gemm.lisp
source/test-suite/test-llm.lisp
source/test-suite/test-normalization.lisp
source/test-suite/test-rope.lisp

numerical accuracy stuff

---

Readme.md
source/apis/documentation.lisp
source/apis/package.lisp
source/apis/tensor.lisp

Full Lisp Examples in Readme.md

---

source/apis/iseq.lisp
source/codegen/expr.lisp
source/codegen/helpers.lisp
source/codegen/jit.lisp
source/codegen/rewriting-rules.lisp
source/codegen/scop.lisp
source/codegen/shape-inference.lisp
source/common/contextvar.lisp
source/isl/isl-object.lisp

Translate Everything into Polyhedral IR

---

source/codegen/shape-inference.lisp
source/test-suite/test-scheduler.lisp

Opt: Always merge broadcasted dims

---

source/common/contextvar.lisp

hotfix: AUTO_SCHEDULER=0 in default

---

.github/workflows/benchmark.yml
source/avm/caten.avm.asd
source/avm/lisp-backend.lisp
source/avm/opset.lisp
source/avm/package.lisp
source/avm/profile.lisp
source/avm/runtime.lisp
source/codegen/caten.codegen.asd
source/codegen/jit.lisp
source/codegen/runner.lisp
source/common/contextvar.lisp

smth looking like:
```
================================================================================
PROFILE=1:
[0]   | ALLOCATE | 0.0001 MB | NIL INT64
[1]   |    VM    | 0.000001s | LOAD 
[2]   | ALLOCATE | 0.0001 MB | NIL UINT64
[3]   |    VM    | 0.000000s | LOAD 
[4]   |   LOAD   | 0.0000 MB | (1 1) FLOAT32
[5]   | ALLOCATE | 0.0001 MB | NIL INT64
[6]   |    VM    | 0.000000s | LOAD 
[7]   |    VM    | 0.000006s | ADD 
[8]   |    VM    | 0.000001s | MUL 
[9]   | ALLOCATE | 0.0011 MB | (1 1 1 34) FLOAT32
[10]  |    VM    | 0.000000s | LOAD 
[11]  |    VM    | 0.000000s | ADD 
[12]  |  KERNEL  | 0.000000s | (1 1 1 34) | CLANG | FUSED_TRANSFORMER_TRIUNODE_ARGMAXNODE_MATMUL866898
[13]  |   LOAD   | 1235.1161 MB | (50257 768) FLOAT32
[14]  | ALLOCATE | 0.0001 MB | NIL INT64
[15]  | …
```

Enhancement: PROFILE=1

---

.github/workflows/tests_on_push.yml
source/codegen/blueprint.lisp
source/common/contextvar.lisp
source/test-suite/test-scheduler.lisp

- OPTIMIZE=0 does nothing
- OPTIMIZE=1 is allowed to apply one or few shot search (Make sure CI is tested with this mode)
- OPTIMIZE=2 to generate fully optimized kernel (Benchmarks are tested with this mode)

Refactor: Rename NOOPT -> OPTIMIZE

---

caten.asd
mkdocs.yml
source/api/caten.api.asd
source/nn/caten.nn.asd

Refactor: caten.apis.asd -> caten.api.asd

---

mkdocs.yml
source/api/documentation.lisp

for naming convention consistency, refactor and adapt the documentation entries for api.facet

20250108 refactor facet api naming

---

external/gguf/tensor-info.lisp
source/api/documentation.lisp
source/api/facets.lisp
source/api/package.lisp
source/api/tensor.lisp
source/byoc/metal.lisp
source/codegen/auto-scheduler/ast-parser.lisp
source/codegen/backend.lisp

Enhancement: Global Runtime
